# Generated by Django 2.1.3 on 2018-12-19 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacanciesandsvs', '0002_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
