# Generated by Django 2.1.3 on 2018-12-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='Nurkhan', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='Zhumash', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.IntegerField(default=123),
        ),
        migrations.AddField(
            model_name='user',
            name='skype',
            field=models.CharField(default='asdasd', max_length=255),
        ),
    ]
