# Generated by Django 2.1.3 on 2018-12-18 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20181218_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.IntegerField(default=123),
        ),
        migrations.AddField(
            model_name='user',
            name='skype',
            field=models.CharField(default='asd', max_length=255),
        ),
    ]
