# Generated by Django 2.1.3 on 2018-12-18 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_auto_20181218_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='skype',
            field=models.CharField(max_length=255),
        ),
    ]
