# Generated by Django 2.1.3 on 2018-12-19 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_auto_20181219_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_type',
            field=models.CharField(choices=[('OOO', 'Общество с ограниченной ответственностью'), ('PAO', 'Публичное акционерное общество'), ('AO', 'Акционерное общество'), ('UP', 'qwe'), ('TOO', 'Individual P.'), ('IP', 'Individual P.')], default='Individual P.', max_length=255),
        ),
    ]
