# Generated by Django 2.1.3 on 2018-12-19 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_auto_20181220_0541'),
        ('companies', '0003_auto_20181219_2258'),
    ]

    operations = [
    ]
