# Generated by Django 2.1.3 on 2018-12-20 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_merge_20181220_0554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_type',
            field=models.CharField(choices=[('OOO', 'Общество с ограниченной ответственностью'), ('PAO', 'Публичное акционерное общество'), ('AO', 'Акционерное общество'), ('UP', 'Учебное производство'), ('TOO', 'Товарищество с ограниченной ответственностью '), ('IP', 'Индивидуальный предприниматель'), ('AOO', 'Автономная организация образования'), ('ZAO', 'Закрытое акцтонерное общество'), ('OTHER', 'Другое')], default='Individual P.', max_length=255),
        ),
    ]
