# Generated by Django 2.1.3 on 2018-12-20 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_auto_20181220_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_type',
            field=models.CharField(choices=[('OOO', 'Общество с ограниченной ответственностью'), ('PAO', 'Публичное акционерное общество'), ('AO', 'Акционерное общество'), ('UP', 'Учебное производство'), ('TOO', 'Товарищество с ограниченной ответственностью '), ('IP', 'Индивидуальный предприниматель'), ('AOO', 'Автономная организация образования'), ('ZAO', 'Закрытое акцтонерное общество'), ('OTHER', 'Другое')], default='Индивидуальный предприниматель', max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='short_description',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='site',
            field=models.URLField(default='', null=True),
        ),
    ]
