# Generated by Django 2.1.3 on 2018-12-20 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='images\\default_image.jpg', upload_to='images'),
        ),
    ]
