# Generated by Django 2.1.3 on 2018-12-19 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities.City'),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
